# Configuration for Alacritty, the GPU enhanced terminal emulator.

font:
  # The size to use.
  size: 17
  # The normal (roman) font face to use.
  normal:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Italic

  offset:
    y: 10

  glyph_offset:
    y: 6
